/**
 * @file	GTGlyphSentenct.m
 * @brief	Define GTGlyphCharacter enum
 * @par Copyright
 *   Copyright (C) 2015-2016 Steel Wheels Project
 * @par Reference
 *   Web page : http://www.ingress.tv/2-glyph-hack-sequences.html
 */

import Foundation

public class GTGlyphSentence
{
	public static let glyphSequence1: Array<Array<GTGlyphCharacter>> = [
		[.Gain		],
		[.Old		],
		[.Past		],
		[.Destroy	],
		[.Breathe	],
		[.Live		],
		[.Civilization	],
		[.Defend	],
		[.Help		],
		[.Pursue	],
		[.Weak		],
		[.Avoid		],
		[.Rebel		],
		[.Separate	],
		[.Forget	],
		[.Create	],
		[.Advance	],
		[.Distance	],
		[.Outside	],
		[.Path		],
		[.Deteriorate	],
		[.Courage	],
		[.Message	],
		[.Again		],
		[.Repeat	],
		[.Want		],
		[.Discover	],
		[._Self		],
		[.Die		],
		[.Stability	],
		[.Stay		],
		[.Safety	],
		[.Nature	],
		[.Conflict	],
		[.Shaper	],
		[.Attack	],
		[.War		],
		[.Chaos		],
		[.Liberate	],
		[.See		],
		[.Less		],
		[.Now		],
		[.Present	],
		[.Not		],
		[.Inside	],
		[.Answer	],
		[.Fear		],
		[.Hide		],
		[.Destiny	],
		[.Simple	],
		[.More		],
		[.Equal		],
		[.Change	],
		[.Difficult	],
		[.Save		],
		[.Evolution	],
		[.Success	],
		[.Question	],
		[.Escape	],
		[.Complex	],
		[.Idea		],
		[.Clear		],
		[.Retreat	],
		[.Barrier	],
		[.Data		],
		[.Failure	],
		[.Follow	],
		[.Danger	],
		[.Lead		],
		[.Potential	],
		[.Contemplate	],
		[.Use		],
		[.Search	],
		[.New		],
		[.Easy		],
		[.React		],
		[.Have		],
		[.Capture	],
		[.Journey	],
		[.Ignore	],
		[.Lose		],
		[.Improve	],
		[.Future	],
		[.Pure		],
		[.Impure	],
		[.Imperfect	],
		[.Lie		],
		[.Together	],
		[.Resistance	],
		[.Struggle	],
		[.Harm		],
		[.Enlightenment	],
		[.Balance	],
		[.Perfection	],
		[.Human		],
		[.Body		],
		[.Open		],
		[.Accept	],
		[.Nourish	],
		[.Recharge	],
		[.Repair	],
		[.Mind		],
		[.Soul		],
		[.End		],
		[.All		],
		[.CloseAll	],
		[.OpenAll	],
		[.Strong	],
		[.XM		],
		[.Truth		],
		[.Portal	],
		[.Harmony	],
		[.Peace		]
	]

	public static let glyphSequence2: Array<Array<GTGlyphCharacter>> = [
		[.Civilization, 	.Chaos		],
		[.Pursue,		.XM		],
		[.Pursue, 		.Truth		],
		[.Separate, 		.War		],
		[.Create, 		.Danger		],
		[.Path, 		.Perfection	],
		[.Discover, 		.Safety		],
		[.Discover, 		.Lie		],
		[.Discover, 		.Portal		],
		[.Attack, 		.Chaos		],
		[.Attack, 		.Difficult	],
		[.Liberate, 		.XM		],
		[.Question,		.War		],
		[.Lead,			.Enlightenment	],
		[.Search,		.Potential	],
		[.Search,		.Past		],
		[.Capture,		.Portal		],
		[.Pure,			.Truth		],
		[.Pure,			.Body		],
		[.Pure,			.Human		],
		[.Nourish,		.Journey	],
		[.All,			.Chaos		],
		[.OpenAll,		.Truth		]
	]

	public static let glyphSequence3: Array<Array<GTGlyphCharacter>> = [
		[.Destroy,	.Difficult,	.Barrier	],
		[.Gain,		.Civilization,	.Peace		],
		[.Destroy,	.Weak,		.Civilization	],
		[.Destroy,	.Destiny,	.Barrier	],
		[.Civilization,	.War,		.Chaos		],
		[.Avoid,	.Destiny,	.Lie		],
		[.Avoid,	.Complex,	.Conflict	],
		[.Separate,	.Future,	.Evolution	],
		[.Path,		.Peace,		.Difficult	],
		[.Again,	.Journey,	.Outside	],
		[.Discover,	.Shaper,	.Lie		],
		[.Discover,	.Pure,		.Truth		],
		[.Nature,	.Pure,		.Defend		],
		[.War,		.Create,	.Danger		],
		[.War,		.Destroy,	.Future		],
		[.Attack,	.Difficult,	.Future		],
		[.Attack,	.Shaper,	.Evolution	],
		[.Liberate,	.Portal,	.Potential	],
		[.Inside,	.Mind,		.Future		],
		[.Fear,		.Chaos,		.XM		],
		[.Change,	.Human,		.Future		],
		[.Question,	.Shaper,	.Chaos		],
		[.Question,	.Hide,		.Truth		],
		[.Question,	.Conflict,	.Data		],
		[.Escape,	.Impure,	.Evolution	],
		[.Complex,	.Journey,	.Future		],
		[.Follow,	.Pure,		.Journey	],
		[.Lead,		.Resistance,	.Question	],
		[.React,	.Impure,	.Civilization	],
		[.Capture,	.Shaper,	.Portal		],
		[.Journey,	.Inside,	.Soul		],
		[.Lose,		.Attack,	.Retreat	],
		[.Improve,	.Advance,	.Present	],
		[.Improve,	.Human,		.Shaper		],
		[.Future,	.Equal,		.Past		],
		[.Together,	.Pursue,	.Safety		],
		[.Harm,		.Danger,	.Avoid		],
		[.Perfection,	.Path,		.Peace		],
		[.Mind,		.Open,		.Live		],
		[.All,		.XM,		.Liberate	],
		[.OpenAll,	.Portal,	.Success	],
		[.XM,		.Nourish,	.Civilization	],
		[.Truth,	.Nourish,	.Soul		]
	]

	public static let glyphSequence4: Array<Array<GTGlyphCharacter>> = [
	[.Gain,		.Portal,	.Attack,	.Weak		],
	[.Past,		.Again,		.Present, 	.Again		],
	[.Destroy,	.Destiny,	.Human,		.Lie		],
	[.Destroy,	.Complex,	.Shaper,	.Lie		],
	[.Restraint,	.Path,		.Gain,		.Harmony	],
	[.Restraint,	.Fear,		.Avoid,		.Danger		],
	[.Breathe,	.Again,		.Journey,	.Again		],
	[.Breathe,	.Nature,	.Perfection,	.Harmony	],
	[.Defend,	.Message,	.Answer,	.Idea		],
	[.Help,		.Gain,		.Create,	.Pursue 	],
	[.Help,		.Shaper,	.Create,	.Future		],
	[.Avoid,	.XM,		.Message,	.Lie		],
	[.Separate,	.Weak,		.Ignore,	.Truth		],
	[.Forget,	.Conflict,	.Accept,	.War		],
	[.Create,	.Distance,	.Impure,	.Path		],
	[.Create,	.Future,	.Not,		.War		],
	[.Create,	.Future,	.Change,	.Destiny	],
	[.Advance,	.Civilization,	.Repeat,	.Failure	],
	[.Path,		.Restraint,	.Strong,	.Safety		],
	[.Deteriorate,	.Human,		.Weak,		.Rebel		],
	[.Courage,	.War,		.Shaper,	.Future		],
	[.Stay,		.Together,	.Defend,	.Truth		],
	[.Shaper,	.See,		.Potential,	.Evolution	],
	[.Shaper,	.Portal,	.Mind,		.Restraint	],
	[.Shaper,	.Past,		.Present,	.Future		],
	[.Shaper,	.Mind,		.Complex,	.Harmony	],
	[.Shaper,	.Have,		.Strong,	.Path		],
	[.Shaper, 	.Chaos,		.Pure,		.Harm		],
	[.Shaper,	.Message,	.End,		.Civilization	],
	[.Attack, 	.Weak,		.Shaper,	.Lie		],
	[.Attack,	.Resistance,	.Pursue,	.Enlightenment	],
	[.Attack,	.Enlightenment,	.Pursue,	.Resistance	],
	[.Chaos,	.Barrier,	.Shaper,	.Portal		],
	[.Liberate,	.XM,		.Portal,	.Together	],
	[.See,		.Truth,		.See,		.Future		],
	[.Less,		.Chaos,		.More,		.Stability	],
	[.Less,		.Truth,		.More,		.Chaos		],
	[.Less,		.Soul,		.More,		.Mind		],
	[.Inside,	.Mind,		.Journey,	.Perfection	],
	[.Hide,		.Impure,	.Human,		.Thought	],
	[.Simple,	.Civilization,	.Impure,	.Weak		],
	[.Simple,	.Truth,		.Breathe,	.Nature		],
	[.Simple,	.Message,	.Complex,	.Idea		],
	[.Change,	.Human,		.Potential,	.Use		],
	[.Change,	.Future,	.Capture,	.Destiny	],
	[.Change,	.Body,		.Improve,	.Human		],
	[.Question,	.Truth,		.Gain,		.Future		],
	[.Escape,	.Simple,	.Human,		.Future		],
	[.Complex,	.Shaper,	.Civilization,	.Strong		],
	[.Clear,	.Mind,		.Open,		.Mind		],
	[.Follow,	.Shaper,	.Portal,	.Message	],
	[.Lead,		.Pursue,	.React,		.Defend 	],
	[.Contemplate,	.Complex,	.Shaper,	.Truth		],
	[.Contemplate,	.Complex,	.Shaper,	.Civilization	],
	[.Contemplate,	._Self,		.Path,		.Truth		],
	[.Search,	.Truth,		.Save,		.Civilization	],
	[.Search,	.XM,		.Save,		.Portal		],
	[.Search,	.Data,		.Discover,	.Path		],
	[.Capture,	.Fear,		.Discover,	.Courage	],
	[.Journey,	.Inside,	.Improve,	.Soul		],
	[.Ignore,	.Human,		.Chaos,		.Lie		],
	[.Lose,		.Danger,	.Gain,		.Safety		],
	[.Improve,	.Body,		.Pursue,	.Journey	],
	[.Improve,	.Body,		.Mind,		.Soul		],
	[.Improve,	.Mind,		.Journey,	.Inside		],
	[.Together,	.Discover,	.Harmony,	.Equal		],
	[.Struggle,	.Improve,	.Human,		.Soul		],
	[.Struggle,	.Defend,	.Shaper,	.Danger		],
	[.Perfection,	.Balance,	.Safety,	.All		],
	[.Human,	.Have,		.Impure,	.Civilization	],
	[.Human,	.Soul,		.Strong,	.Pure		],
	[.Human,	.Past,		.Present,	.Future		],
	[.Nourish,	.XM,		.Create,	.Thought	],
	[.Soul,		.Rebel,		.Human,		.Die		],
	[.All,		.Chaos,		.Inside,	.Body		],
	[.CloseAll,	.OpenAll,	.Discover,	.Truth		],
	[.Strong,	.Idea,		.Pursue,	.Truth		],
	[.Strong,	.Together,	.Avoid,		.War		],
	[.Strong,	.Resistance,	.Capture,	.Portal		],
	[.XM,		.Have,		.Mind,		.Journey	],
	[.XM,		.Die,		.Chaos,		.Live		],
	[.Truth,	.Idea,		.Discover,	.XM		],
	[.Portal,	.Have,		.Truth,		.Data		],
	[.Portal,	.Potential,	.Change,	.Future		],
	[.Portal,	.Die,		.Civilization,	.Die		],
	[.Portal,	.Change,	.Civilization,	.End		],
	[.Peace,	.Path,		.Nourish,	.Present	],
	]

	public static let glyphSequence5: Array<Array<GTGlyphCharacter>> = [
	[.Gain,		.Truth,		.Open,		.Human,		.Soul		],
	[.Old,		.Nature,	.Less,		.Strong,	.Now		],
	[.Past,		.Chaos,		.Create,	.Future,	.Harmony	],
	[.Past,		.Path,		.Create,	.Future,	.Journey,	],
	[.Destroy,	.Lie,		.Inside,	.Gain,		.Soul,		],
	[.Destroy,	.Civilization,	.End,		.Conflict,	.War		],
	[.Breathe,	.Inside,	.XM,		.Lose,		._Self		],
	[.Defend,	.Destiny,	.Defend,	.Human,		.Civilization	],
	[.Defend,	.Human,		.Civilization,	.XM,		.Message	],
	[.Defend,	.Human,		.Civilization,	.Shaper,	.Lie		],
	[.Defend,	.Human,		.Civilization,	.Portal,	.Data		],
	[.Defend,	.Human,		.Civilization,	.Shaper,	.Portal 	],
	[.Help,		.Enlightenment,	.Capture,	.All,		.Portal		],
	[.Help,		.Resistance,	.Capture,	.All,		.Portal		],
	[.Help,		.Human,		.Civilization,	.Pursue,	.Destiny	],
	[.Pursue,	.Path,		.Outside,	.Shaper,	.Lie		],
	[.Pursue,	.Conflict,	.War,		.Advance,	.Chaos		],
	[.Weak,		.Human,		.Destiny,	.Destroy,	.Civilization	],
	[.Avoid,	.Chaos,		.Repair,	.Potential,	.War		],
	[.Avoid,	.Perfection,	.Stay,		.Human,		._Self		],
	[.Avoid,	.Chaos,		.Avoid,		.Shaper,	.Lie		],
	[.Rebel,	.Thought,	.Evolution,	.Destiny,	.Now		],
	[.Separate,	.Mind,		.Body,		.Discover,	.Enlightenment	],
	[.Separate,	.Truth,		.Lie,		.Shaper,	.Future 	],
	[.Forget,	.Past,		.See,		.Present,	.Danger 	],
	[.Forget,	.War,		.See,		.Distance,	.Harmony,	],
	[.Create,	.Pure,		.Future,	.Not,		.War		],
	[.Create,	.Pure,		.Future,	.Human,		.Civilization	],
	[.Create,	.Separate,	.Path,		.End,		.Journey	],
	[.Advance,	.Civilization,	.Pursue,	.Shaper,	.Path		],
	[.Distance,	._Self,		.Avoid,		.Human,		.Lie		],
	[.Courage,	.Attack,	.Shaper,	.Portal,	.Together	],
	[.Want, 	.Truth,		.Pursue,	.Difficult,	.Path		],
	[.Stay,		.Strong,	.Together,	.Defend,	.Resistance	],
	[.Shaper,	.Portal,	.Data,		.Create,	.Chaos		],
	[.Shaper,	.Portal,	.Message,	.Destroy,	.Civilization	],
	[.Shaper,	.Want,		.Human,		.Mind,		.Future		],
	[.Shaper,	.Lead,		.Human,		.Complex,	.Journey	],
	[.Chaos,	.War,		.Conflict,	.Discover,	.Peace		],
	[.Liberate,	.Portal,	.Liberate,	.Human,		.Mind		],
	[.Present,	.Chaos,		.Create,	.Future,	.Civilization	],
	[.Inside,	.Mind,		.Inside,	.Soul,		.Harmony	],
	[.Answer,	.Question,	.Discover,	.Difficult,	.Truth		],
	[.Hide,		.Struggle,	.Advance,	.Strong,	.Together	],
	[.Simple,	.Truth,		.Shaper,	.Destroy,	.Civilization	],
	[.Simple,	.Old,		.Truth,		.Journey,	.Inside		],
	[.More,		.Data,		.Gain,		.Portal,	.Advance	],
	[.Save,		.Human,		.Civilization,	.Destroy,	.Portal		],
	[.Question,	.Less,		.Forget,	.All,		.Lie		],
	[.Escape,	.Body,		.Journey,	.Outside,	.Present	],
	[.Escape,	.Body,		.Mind,		._Self,		.Want		],
	[.Clear,	.Mind,		.Liberate,	.Barrier,	.Body		],
	[.Contemplate,	.Future,	.Not,		.Shaper,	.Path		],
	[.Contemplate,	.Restraint,	.Discover,	.More,		.Courage	],
	[.Use,		.Restraint,	.Follow,	.Easy,		.Path		],
	[.Use,		.Mind,		.Use,		.Courage,	.Change		],
	[.Search,	.Destiny,	.Create,	.Pure,		.Future		],
	[.Easy,		.Path,		.Future,	.Follow,	.Shaper	],
	[.React,	.Rebel,		.Question,	.Shaper,	.Lie		],
	[.Capture,	.Portal,	.Defend,	.Portal,	.Courage	],
	[.Lose,		.Shaper,	.Message,	.Gain,		.Chaos		],
	[.Pure,		.Human,		.Failure,	.Now,		.Chaos		],
	[.Imperfect,	.XM,		.Message,	.Human,		.Chaos		],
	[.Imperfect,	.Truth,		.Accept,	.Complex,	.Answer		],
	[.Human,	.Shaper,	.Together,	.Create,	.Destiny	],
	[.Human,	.Not,		.Together,	.Civilization,	.Deteriorate 	],
	[.Recharge,	.Present,	.Recharge,	.Human,		.Soul		],
	[.Repair,	.Soul,		.Less,		.Human,		.Harm		],
	[.CloseAll,	.Thought,	.Past,		.Present,	.Future		],
	[.Strong,	.Together,	.War,		.Together,	.Destiny	],
	[.Strong,	.Together,	.War,		.Together,	.Chaos		],
	[.XM,		.Path,		.Future,	.Destiny,	.Harmony	],
	[.XM,		.Create,	.Complex,	.Human,		.Destiny	],
	[.Portal,	.Create,	.Danger,	.Pursue,	.Safety		],
	[.Portal,	.Potential,	.Help,		.Human,		.Future		],
	[.Portal,	.Barrier,	.Defend,	.Human,		.Shaper	],
	[.Portal,	.Improve,	.Human,		.Future,	.Civilization	],
	]
}

